### ISSUE TITLE
officebox@3.0.6: Hash check failed

### ISSUE THREAD

**Issue by diklios5768** [ygguorun/scoop-bucket#1]
Hash check failed!
App:         ygguorun/officebox
URL:         http://files.wofficebox.com/officebox/download/OfficeBox%E5%AE%98%E6%96%B9%E7%BB%BF%E8%89%B2%E7%89%88.zip
First bytes: 80 75 3 4 20 0 0 0
Expected:    3058d34c2553fca1f46234acc8acecf4578cc73d65626055e536c2085e96acc2
Actual:      51f96c4a5123245a50efce9ab71b0063bf9e9708ee32b0c35a348119ae9e07ad

**Comment by ygguorun** [comment]
Fix in 58287bb3fd5e94c53094a046f6319a15bf721aeb
