### ISSUE TITLE
CloudCompare Hash check failed!

### ISSUE THREAD

**Issue by rkolka** [ygguorun/scoop-bucket#2]
Checking hash of CloudCompare_v2.12.beta_bin_x64.7z ... ERROR Hash check failed!
App:         CloudCompare
URL:         http://www.danielgm.net/cc/release/CloudCompare_v2.12.beta_bin_x64.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    bac42b988ebefa9882e5a5428d1d22a8c756a98466f19365e2e02a6be2b43d71
Actual:      117b6143ec3f980c123f54a1db9f0a24b6dad8cd01dfc7306fb9cd406d2cf440

**Comment by ygguorun** [comment]
Fix in 74045ecf
