### ISSUE TITLE
SubRenamer@0.5.0: hash check failed

### ISSUE THREAD

**Issue by dyuu7** [ygguorun/scoop-bucket#6]
It seems that the verification information needs to be updated.

Log:
Installing 'SubRenamer' (0.5.0) [64bit] from ygguorun_scoop-bucket bucket
SubRenamer.v0.5.2.2021-7-10.exe (995.0 KB) [======================================================================] 100%
Checking hash of SubRenamer.v0.5.2.2021-7-10.exe ... ERROR Hash check failed!
App:         ygguorun_scoop-bucket/SubRenamer
URL:         https://github.com/qwqcode/SubRenamer/releases/download/0.5.0/SubRenamer.v0.5.2.2021-7-10.exe#/SubRenamer.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    669b31e82f7fda1cd146407acc5645c7a90a0985e625c123560c22ad1908bdb9
Actual:      bf68db2f2d8f1e429cf9451c03b55ac3b810d7e318d8d75456d91d069cf6d43d

**Comment by ygguorun** [comment]
Thanks for your feedback.
