### ISSUE TITLE
adrive@6.1.0: download via aria2 failed

### ISSUE THREAD

**Issue by zhangxiaochang** [ygguorun/scoop-bucket#9]
大佬 我这个安装阿里云这个一直报403是为啥啊 浏览器可以访问

**Comment by ygguorun** [comment]
软件下载链接访问需要user-agent，目前 scoop 暂不支持设置此参数。

我用 cloudflare workers 中转了一下，可以更新后再试一试，不过下载速度可能会慢一点。
